# Generated by Django 3.2.11 on 2026-01-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentface',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='studentface',
            name='liveness_passed',
        ),
    ]
