# Generated by Django 3.2.11 on 2026-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20260115_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(max_length=50),
        ),
    ]
