# Generated by Django 3.2.11 on 2026-01-03 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=150)),
                ('institute', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, choices=[('phd', 'PhD'), ('masters', 'Masters'), ('bachelors', 'Bachelors'), ('diploma', 'Diploma'), ('other', 'Other')], max_length=50, null=True)),
                ('experience', models.CharField(blank=True, choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], max_length=20, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
